#User MVC Board
#/board_list.do=execute|net.daum.controller.BoardListController
#/board_write.do=execute|net.daum.controller.BoardWriteController
#/board_write_ok.do=execute|net.daum.controller.BoardWriteOKController
#/board_cont.do=execute|net.daum.controller.BoardContController
#/board_reply_ok.do=execute|net.daum.controller.BoardReplyOKController
#/board_edit_ok.do=execute|net.daum.controller.BoardEditOKController
#/board_del_ok.do=execute|net.daum.controller.BoardDeLOKController

#User Gongji
#/gongji_list.do=execute|net.daum.controller.GongjiListController
#/gongji_cont.do=execute|net.daum.controller.GongjiContController

#User MVC member
/member_login.do=execute|net.daum.controller.MemberLoginController
/member_join.do=execute|net.daum.controller.MemberJoinController
/member_idcheck.do=execute|net.daum.controller.MemberIDCheckController
/member_join_ok.do=execute|net.daum.controller.MemberJoinOKController
/zip_find.do=execute|net.daum.controller.ZipFindController
/zip_find_ok.do=execute|net.daum.controller.ZipFindOKController
/pwd_find.do=execute|net.daum.controller.PwdFindController
/pwd_find_ok.do=execute|net.daum.controller.PwdFindOKController
/member_login_ok.do=execute|net.daum.controller.MemberLoginOKController
/index.do=execute|net.daum.controller.IndexController
/member_logout.do=execute|net.daum.controller.MemberLogOutController
/member_edit.do=execute|net.daum.controller.MemberEditController
/member_edit_ok.do=execute|net.daum.controller.MemberEditOKController
/member_del.do=execute|net.daum.controller.MemberDeLController
/member_del_ok.do=execute|net.daum.controller.MemberDeLOKController

#User MVC Bbs
#/bbs_write.do=execute|net.daum.controller.BbsWriteController
#/bbs_write_ok.do=execute|net.daum.controller.BbsWriteOKController
#/bbs_list.do=execute|net.daum.controller.BbsListController
#/bbs_cont.do=execute|net.daum.controller.BbsContController
#/bbs_reply_ok.do=execute|net.daum.controller.BbsReplyOKController
#/bbs_edit_ok.do=execute|net.daum.controller.BbsEditOKController
#/bbs_del_ok.do=execute|net.daum.controller.BbsDeLOKController

#Admin Login Form page
#/admin_login.do=execute|net.daum.controller.AdminLoginController
#/admin_login_ok.do=execute|net.daum.controller.AdminLoginOKController
#/admin_index.do=execute|net.daum.controller.AdminIndexController
#/admin_logout.do=execute|net.daum.controller.AdminLogOutController

#Admin Board
#/admin_board_list.do=execute|net.daum.controller.AdminBoardListController
#/admin_board_write.do=execute|net.daum.controller.AdminBoardWriteController
#/admin_board_write_ok.do=execute|net.daum.controller.AdminBoardWriteOKController
#/admin_board_cont.do=execute|net.daum.controller.AdminBoardContController
#/admin_board_edit_ok.do=execute|net.daum.controller.AdminBoardEditOKController
#/admin_board_del.do=execute|net.daum.controller.AdminBoardDelOKController

#Admin Bbs
#/admin_bbs_list.do=execute|net.daum.controller.AdminBbsListController
#/admin_bbs_write.do=execute|net.daum.controller.AdminBbsWriteController
#/admin_bbs_write_ok.do=execute|net.daum.controller.AdminBbsWriteOKController
#/admin_bbs_cont.do=execute|net.daum.controller.AdminBbsContController
#/admin_bbs_edit_ok.do=execute|net.daum.controller.AdminBbsEditOKController
#/admin_bbs_del.do=execute|net.daum.controller.AdminBbsDelOKController

#Admin Gongji
#/admin_gongji_list.do=execute|net.daum.controller.AdminGongjiListController
#/admin_gongji_write.do=execute|net.daum.controller.AdminGongjiWriteController
#/admin_gongji_write_ok.do=execute|net.daum.controller.AdminGongjiWriteOKController
#/admin_gongji_cont.do=execute|net.daum.controller.AdminGongjiContController
#/admin_gongji_edit_ok.do=execute|net.daum.controller.AdminGongjiEditOKController
#/admin_gongji_del.do=execute|net.daum.controller.AdminGongjiDelOKController

#Admin Member
#/admin_member_list.do=execute|net.daum.controller.AdminMemberListController
#/admin_member_info.do=execute|net.daum.controller.AdminMemberInfoController
#/admin_member_edit_ok.do=execute|net.daum.controller.AdminMemberEditOKController
#/admin_member_del.do=execute|net.daum.controller.AdminMemberDelOKController